---Q1 - Total Transactions - “We need to quickly understand the total volume of transactions
---processed in the dataset to gauge the scale of our commercial operations. How many transactions have been recorded overall?”

SELECT count(*) AS total_transactions
FROM purchases;


-------------

---Q2 – Date Range of Transactions - “We need to determine the temporal coverage of our dataset. 
---What is the earliest and latest transaction date recorded so we can understand the time span of our analysis?”


SELECT min(date) AS earliest_transaction, max(date) AS latest_transaction
FROM purchases;


-------------

---Q3 – Missing Values Check - “Before performing any analysis, we need to ensure data quality. 
---Identify how many missing or NULL values exist for each column in the dataset to understand potential gaps or issues.”

SELECT
	sum(CASE When "Date" is null then 1 else 0 end) as null_date,
	sum(CASE When "Gender" is null then 1 else 0 end) as null_gender,
	sum(CASE When "Age" is null then 1 else 0 end) as null_age,
	sum(CASE When "Product Category" is null then 1 else 0 end) as null_prod_cat,
	sum(CASE When "Quantity" is null then 1 else 0 end) as null_quantity,
	sum(CASE When "Price Per Unit" is null then 1 else 0 end) as null_price_per_unit,
	sum(CASE When "Total Amount" is null then 1 else 0 end) as null_total_amount
FROM purchases;


-------------

---Q4 – Monthly Revenue - “We need to track revenue trends over time. 
---Calculate the total revenue generated for each month to understand seasonality and monthly performance patterns.”

SELECT 
	sum("Total Amount") as Total,
	strftime('%Y', Date) as Year,
	strftime('%m', Date) as Month
FROM purchases
GROUP BY Year, Month
ORDER BY Year, Month


-------------


---Q5 – Top Product Categories - “We want to identify which product categories are driving the most revenue. 
---Rank the product categories from highest to lowest total revenue to guide commercial focus and inventory decisions.”

SELECT
	sum("Total Amount") as Total,
	"Product Category" as Prod_Cat
FROM purchases
GROUP BY "Product Category"
ORDER BY Total DESC


-------------


---Q6 – Average Order Value per Customer - “We want to understand the typical spend per customer per transaction. 
---Calculate the average order value for each customer to identify spending patterns and inform promotional strategies.”

SELECT 
	AVG("Total Amount") AS AOV
FROM purchases


-------------


---Q7 – Revenue by Gender - “We want to analyze revenue distribution between genders. 
---Calculate the total revenue generated by each gender to understand spending patterns and inform targeted commercial strategies.”

SELECT
	sum("Total Amount") as Total,
	Gender
FROM purchases
GROUP BY Gender;


-------------


---Q8 – Average Age per Product Category - “We want to understand the typical age of customers purchasing each product category. 
---Calculate the average age per product category to identify target demographics for marketing and product strategy.”

SELECT
	ROUND(avg(Age), 2) as average_age,
	"Product Category"
FROM purchases
GROUP BY "Product Category"


-------------


---Q9 – Quantity Sold per Product Category - “We want to understand sales volume across product categories. 
---Calculate the total quantity sold for each product category to identify which categories are driving volume rather than just revenue.”

SELECT
	sum(Quantity) as Total_quantity_sold,
	"Product Category" 
FROM purchases
GROUP BY  "Product Category" 


-------------


---Q10 – Price per Unit Distribution - “We want to understand how product pricing is distributed across transactions. 
---Analyze the distribution of price per unit to identify typical price ranges and detect potential outliers.”

SELECT
	ROUND(avg("Price per Unit"), 2) as avg_pp_u,
	min("Price per Unit") as min_pp_u,
	max("Price per Unit") as max_pp_u,
	"Product Category"
FROM purchases
GROUP BY "Product Category"


-------------


---Q11 – High-Value Transactions - “We want to identify unusually high-value transactions that may indicate VIP customers, data issues, or exceptional purchasing behavior. 
---Retrieve all transactions where the total amount is significantly higher than average.”

SELECT *
FROM purchases
WHERE "Total Amount" > (
	SELECT avg("Total Amount")
	FROM purchases
)
ORDER BY "Total Amount" DESC
LIMIT 10
;


-------------


---Q12 – Revenue Contribution by Product Category (%) - “We want to understand which product categories are truly driving the business. 
---Calculate the percentage contribution of each product category to the total revenue, so we can prioritize commercial focus and resource allocation.”

WITH total_revenue AS (
	SELECT
		SUM("Total Amount") AS Total
	FROM purchases
)
SELECT
	p."Product Category",
	SUM(p."Total Amount") AS category_revenue,
	ROUND(
		(SUM(p."Total Amount") / CAST(tr.total AS REAL)) * 100,
		2
	) AS revenue_percentage
FROM purchases p
CROSS JOIN total_revenue tr
GROUP BY p."Product Category"
ORDER BY revenue_percentage DESC;


-------------


---Q13 – Pareto Analysis (80/20 Rule) - “We want to identify which product categories drive the majority of our revenue.
---Using the 80/20 principle, determine which product categories cumulatively account for approximately 80% of total revenue.”

WITH category_revenue AS(
	SELECT
		"Product Category",
		sum("Total Amount") AS revenue
	FROM purchases
	GROUP BY "Product Category"
),

total_revenue AS(
	SELECT
		sum(revenue) AS Total
	FROM category_revenue
),

revenue_with_percentage AS(
	SELECT
		cr."Product Category",
		cr.revenue,
		ROUND(
			(cr.revenue / CAST(tr.total AS REAL)) * 100,
			2
		) AS revenue_percentage
	FROM category_revenue cr
	CROSS JOIN total_revenue tr
)

SELECT
	"Product Category",
	revenue,
	revenue_percentage,
	ROUND(
		sum(revenue_percentage) OVER(
			ORDER BY revenue_percentage DESC
		),
		2
	) AS cumulative_percentage
FROM revenue_with_percentage
ORDER BY revenue_percentage DESC;


-------------














